// Generated by CoffeeScript 1.8.0
angular.module('Feniks', []).config([
  '$interpolateProvider', function($interpolateProvider) {
    $interpolateProvider.startSymbol('[[');
    return $interpolateProvider.endSymbol(']]');
  }
]).controller('Main', function($scope, $timeout, $window, $interval, $http) {
  var changePhoto, groupPhotos;
  $scope.path = $scope.page = $window.location.pathname;
  if ($scope.path.indexOf("photo") !== -1) {
    $scope.page = '/photo/';
  }
  $scope.boxBlink = true;
  $scope.videos = [];
  changePhoto = true;
  groupPhotos = {
    "true": 'TXa4PJIv18g',
    "false": 't6G67b6D_qQ'
  };
  $scope.groupPhoto = groupPhotos[changePhoto];
  if ($scope.page === '/about/') {
    $interval(function() {
      changePhoto = !changePhoto;
      return $scope.groupPhoto = groupPhotos[changePhoto];
    }, 5000);
  }
  $http.get("https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=UCgUafpxg3uzUhhMHmzwIfdA&maxResults=10&order=date&key=AIzaSyAwgN8e2f4lqGwtIIPp7bcid02EiVtfvH0").success(function(response) {
    angular.forEach(response.items, function(video) {
      if (!video.id.videoId) {
        return;
      }
      return $scope.videos.push({
        id: video.id.videoId,
        title: video.snippet.title,
        description: video.snippet.description,
        img: video.snippet.thumbnails.high.url
      });
    });
    return $timeout(function() {
      return $scope.$broadcast('initColorboxVideo');
    }, 100);
  }).error(function(error) {
    return console.info("Youtube error: ", error);
  });
  return false;
}).directive('autoHeight', function($window) {
  return {
    restrict: 'AC',
    link: function(scope, elm, attrs) {
      var height;
      height = $window.innerHeight;
      scope[attrs.autoHeight + "MinHeight"] = height - 170 + 'px';
      return $window.onresize = function(e) {
        height = $window.innerHeight;
        return scope[attrs.autoHeight + "MinHeight"] = height - 170 + 'px';
      };
    }
  };
}).directive('theBox', function($interval) {
  return {
    restrict: 'C',
    link: function(scope, elm, attrs) {
      return $interval(function() {
        return scope.boxBlink = !scope.boxBlink;
      }, 1000);
    }
  };
}).directive('colorbox', function() {
  return {
    restrict: 'A',
    link: function(scope, elm, attrs) {
      var opts;
      opts = {
        rel: 'box',
        title: function() {
          return jQuery(this).attr('title') || "";
        },
        width: "70%",
        maxHeight: "95%",
        current: "{current} из {total}"
      };
      if (attrs.colorbox === 'artists') {
        opts.current = "";
      }
      elm.find(".box").colorbox(opts);
      return scope.$on('initColorboxVideo', function() {
        return elm.find(".youtube").colorbox({
          iframe: true,
          innerWidth: 640,
          innerHeight: 390
        });
      });
    }
  };
}).directive('imgCenter', function() {
  return {
    restrict: 'A',
    link: function(scope, elm) {
      return elm.load(function() {
        var height, width;
        width = this.naturalWidth;
        height = this.naturalHeight;
        elm.parent().css({
          position: "relative"
        });
        if (width / height > 1) {
          return elm.css({
            "position": "absolute",
            "height": "auto",
            "width": "" + (elm.parent().width()) + "px",
            "margin-top": -height * elm.parent().width() / width / 2 + "px",
            "top": "50%",
            "left": "0"
          });
        } else {
          return elm.css({
            "position": "absolute",
            "height": "" + (elm.parent().height()) + "px",
            "width": "auto",
            "margin-left": -width * elm.parent().height() / height / 2 + "px",
            "left": "50%",
            "top": "0"
          });
        }
      });
    }
  };
});
